server:
  port: 8083

spring:
  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fech-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


