package com.bootcamp.coremodule.enums;

public enum AllOrderStatus {
    ORDER_PLACED,
    CANCELLED,
    ORDER_REJECTED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    DELIVERED,
    RETURN_REQUESTED,
    RETURN_REJECTED,
    RETURN_APPROVED,
    PICKUP_INITIATED,
    PICKUP_COMPLETED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    WAITING_FOR_CONFIRMATION,
    CLOSED,
    REQUEST_PROCESSING;
}